version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ticketera_db
    restart: always
    environment:
      POSTGRES_USER: ticketera_user
      POSTGRES_PASSWORD: ticketera_pass_2025
      POSTGRES_DB: ticketera_prod
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ticketera_net

  redis:
    image: redis:7-alpine
    container_name: ticketera_redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - ticketera_net

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ticketera_api
    restart: always
    environment:
      DATABASE_URL: postgres://ticketera_user:ticketera_pass_2025@db:5432/ticketera_prod
      REDIS_URL: redis://redis:6379
      JWT_SECRET: super_secret_event_key_2025_ticketera
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - ticketera_net

networks:
  ticketera_net:
    driver: bridge

volumes:
  pgdata:
